### ISSUE TITLE
Passing a vector will generate exceeds-transaction-limit error

### ISSUE THREAD

**Issue by randywreed** [ColumbusCollaboratory/cognizer#6]
If a vector of texts is passed to cognizer (I've tried this with text_sentiment and text_emotions, where I have a dataframe of with a comments field). I get a response of "exceeds-transaction-limit" after about 50th row. This occurs whether I pass a vector to the function or whether I pass each text separately using a for loop.

**Comment by randywreed** [comment]
I created the following functions for text sentiment and text-emotions that seem to not generate the error. I'm not sure what is different about it since it is mostly based on your code. Still, I submit it to you for inspection to see if it helps you find the problem (or as an alternative if anyone else experiences the sane issue)

library(curl)
library(jsonlite)
#ptype T=Text, E=Emotion
.straight_text_sentiment <- function (ptype, single_vector) {
  msg_row=""
  if (ptype=="T") {
    watcall="https://gateway-a.watsonplatform.net/calls/text/TextGetTextSentiment?"
  } else if (ptype=="E"){
    watcall="https://gateway-a.watsonplatform.net/calls/text/TextGetEmotion?"
  }
  output="json"
  showsource=1
  MY_API<-Sys.getenv("SERVICE_API_KEY")
  parameters <- paste (
    c("apikey", "outputMode", "showSourceText"),
    c(MY_API, output, showsource),
    sep = "=",
    collapse = "&")
  #for (i in 1:length(text_vector)) {
  msg_row<-paste0(watcall, parameters, "&text=",curl_escape(single_vector))
  fout<-curl_fetch_memory(msg_row)
  sent_out<-fromJSON(rawToChar(fout$content))
  return(sent_out)
}
vector_text_sentiment <- function(text_vector) {
  all_out<-vector("list", length(text_vector))
  for (i in 1:length(text_vector)) {
    single_out<-.straight_text_sentiment("T", text_vector[i])
    all_out[i]<-list(single_out)
    
  }
  return(all_out)
}
vector_text_emotion <- function(text_vector) {
  all_out<-vector("list", length(text_vector))
  for (i in 1:length(text_vector)) {
    single_out<-.straight_text_sentiment("E", text_vector[i])
    all_out[i]<-list(single_out)
  }
  return(all_out)
}.

**Comment by slavaua87** [comment]
Hey there!

It sounds like you are hitting daily limits. As of writing, the free account advertises a daily limit of 1000 calls per credential. For alchemy, you can monitor it with http://access.alchemyapi.com/calls/info/GetAPIKeyInfo?apikey=API_KEY. Not sure about other services.

The code uses curl_multi; it sends concurrent requests, but I am not aware of concurrency limits - at least I have not seen anything about it in documentation. I pass hundreds of text values to text_* functions without issues, so I am not sure if the issue is with parallelism and you need to transition to serial looping (or better to block looping to take advantage of concurrency upto the limit).

Here is a possible "explanation" for your results. When I test the code on the free account everything is fine within 1000 calls. After 1000 calls, I expect to be getting all errors, but I do not. IBM still processes some of the inputs while refusing to process others with "daily-transaction-limit-exceeded" message returned. So maybe the issues you are seeing is you are past the limit and the function sometimes works and sometimes does not because IBM is not strict in enforcing the limit. It seems that I tap out at 2135, and after that IBM refuses service systematically.

Let me know if this helps or if I am missing something.

**Comment by randywreed** [comment]
Hi,
The error may have to do concurrency. IBM only allows 1 concurrent request (at least as their support explained it to me). I get cut off after about 50 request (verified by the GetAPIKeyInfo) even though I am well short of the 1000. If I use the code I listed (which does not do concurrent requests) it works without error until I hit the 1000 limit. I suspect that is the root of the error. Here's what IBM support told me:

> Hello
 Randy,

> I  have taken a look at this ticket for you and can confirm that your daily limit is 1000 and you do not seem to be meeting this with individual transactions. Can I ask however if you are trying to run multiple concurrent transactions at the same time with this key? Along with the transaction limit there is a concurrency limit of one transaction at a time. 

> Best  Regards

> Jamie Gilbert

> Watson Developer Cloud Support

**Comment by slavaua87** [comment]
I am not sure what's happening. I just created a free account and analyzed sentiment for a vector of 900 elements with the code below without an issue. I could see parallel requests with nettop and IBM's transaction monitor flying towards the upper limit.

```
key <- "abc"
text_path <- system.file(
  "extdata/text",
  "text_examples.txt",
  package = "cognizer"
)
text <- readLines(text_path)
text <- rep(text, 300)
test <- cognizer::text_sentiment(text, key)
```

Another issue may be the number of characters you are passing in a single element, but from your description it does not sound like it. 

It would be helpful if you described your inputs better and if possible give a reproducible example.
